// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0

package database

import (
	"database/sql"
	"time"

	"github.com/google/uuid"
)

type User struct {
	ID        uuid.UUID
	CreatedAt time.Time
	Email     string
	Name      string
	Password  string
}

type Workspace struct {
	ID          uuid.UUID
	CreatedAt   time.Time
	Name        string
	Email       string
	Address     string
	UserID      uuid.UUID
	DisplayName string
	OpeningTime time.Time
	ClosingTime time.Time
	Logo        sql.NullString
	Description sql.NullString
}
