// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0
// source: workspace.sql

package database

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createWorkspaces = `-- name: CreateWorkspaces :one
INSERT INTO workspaces (id, created_at, name, email, address, user_id, display_name, opening_time, closing_time)
VALUES ($1, $2, $3, $4,$5,$6,$7,$8,$9)
RETURNING id, created_at, name, email, address, user_id, display_name, opening_time, closing_time
`

type CreateWorkspacesParams struct {
	ID          uuid.UUID
	CreatedAt   time.Time
	Name        string
	Email       string
	Address     string
	UserID      uuid.UUID
	DisplayName string
	OpeningTime time.Time
	ClosingTime time.Time
}

func (q *Queries) CreateWorkspaces(ctx context.Context, arg CreateWorkspacesParams) (Workspace, error) {
	row := q.db.QueryRowContext(ctx, createWorkspaces,
		arg.ID,
		arg.CreatedAt,
		arg.Name,
		arg.Email,
		arg.Address,
		arg.UserID,
		arg.DisplayName,
		arg.OpeningTime,
		arg.ClosingTime,
	)
	var i Workspace
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.Name,
		&i.Email,
		&i.Address,
		&i.UserID,
		&i.DisplayName,
		&i.OpeningTime,
		&i.ClosingTime,
	)
	return i, err
}
